### ISSUE TITLE
Editor on Cacti not working (PHP Weathermap version 1.0.0dev)

### ISSUE THREAD

**Issue by pautiina** [howardjones/network-weathermap#126]
Hello.
Editor not work correctly.
When I open editor, browser console have next error:
```
ncaught SyntaxError: Unexpected token <
jquery.min.js:2 jQuery.Deferred exception: fromplug is not defined ReferenceError: fromplug is not defined
    at attach_click_events (http://noc/cacti/plugins/weathermap/editor-resources/editor.js:83:5)
    at HTMLDocument.initJS (http://noc/cacti/plugins/weathermap/editor-resources/editor.js:59:9)
    at j (http://noc/cacti/plugins/weathermap/vendor/jquery/dist/jquery.min.js:2:29999)
    at k (http://noc/cacti/plugins/weathermap/vendor/jquery/dist/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 jQuery.Deferred exception: imlist is not defined ReferenceError: imlist is not defined
    at HTMLDocument.initJS16 (http://noc/cacti/plugins/weathermap/editor-resources/editor16.js:13:17)
    at j (http://noc/cacti/plugins/weathermap/vendor/jquery/dist/jquery.min.js:2:29999)
    at k (http://noc/cacti/plugins/weathermap/vendor/jquery/dist/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught ReferenceError: fromplug is not defined
    at attach_click_events (editor.js:83)
    at HTMLDocument.initJS (editor.js:59)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
jquery.min.js:2 Uncaught ReferenceError: imlist is not defined
    at HTMLDocument.initJS16 (editor16.js:13)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```

and on cacti log:

```
2018/01/31 10:02:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/weathermap/weathermap-cacti10-plugin-editor.php: 25 require_once)(/plugins/weathermap/editor.php: 34 main)(/plugins/weathermap/lib/Weathermap/Editor/EditorUI.php: 932 showMainPage)(/plugins/weathermap/lib/Weathermap/Editor/EditorUI.php: 1123 fetch)(/plugins/weathermap/lib/Weathermap/UI/SimpleTemplate.php: 48 include)(/plugins/weathermap/editor-resources/templates/main-oldstyle.php: 28 CactiErrorHandler)(/lib/functions.php: 4516 cacti_debug_backtrace)
--
2018/01/31 10:02:35 - ERROR PHP NOTICE in Plugin 'weathermap': Use of undefined constant host_url - assumed 'host_url' in file: /var/www/data/cacti/plugins/weathermap/editor-resources/templates/main-oldstyle.php on line: 28

```

**Comment by dabeani** [comment]
same problem here!

**Comment by netniV** [comment]
The second can be fixed by editing `editor-resources/templates/main-oldstyle.php` at line 28 and changing it to:
```php
var host_url = <?php echo $host_url ?>;
```

**Comment by howardjones** [comment]
I was testing this last night after @pautiina mentioned it in the forum, and didn't see any error, using the editor directly (I use `php -S 0.0.0.0:8000` to test). Very odd. Thanks for the correction. The 'return url' is quite likely not passed all the way through. I'll look at that today.

**Comment by netniV** [comment]
That's strange given it's a pure error.  Maybe the error_reporting() isn't set properly if running that way?

**Comment by netniV** [comment]
Maybe try with debuging with:
```
php -S 0.0.0.0:8000 -d error_reporting=22527 -d display_errors=1
```
The number is the number that error_reporting would return after you set the appropriate levels.  The above should be E_ALL & ~E_DEPRECATED

**Comment by howardjones** [comment]
Agreed (re: error reporting).

Also, a bug in your fix ;-) The value for host_url is a string, so the actual change is:

        var host_url = '<?php echo $host_url ?>';

(with the quotes)

Just testing a slightly wider patch that actually sets the value though ;-)

**Comment by howardjones** [comment]
`ncaught SyntaxError: Unexpected token <`

I can't figure out where this is coming from though.

**Comment by pautiina** [comment]
I have update code.
Now when on browser open link `cacti/plugins/weathermap/weathermap-cacti10-plugin-editor.php` for choose map for edit on browser console have next warning and error:
```
jquery.min.js:2 jQuery.Deferred exception: imlist is not defined ReferenceError: imlist is not defined
    at HTMLDocument.initJS16 (http://noc/cacti/plugins/weathermap/editor-resources/editor16.js:13:17)
    at j (http://noc/cacti/plugins/weathermap/vendor/jquery/dist/jquery.min.js:2:29999)
    at k (http://noc/cacti/plugins/weathermap/vendor/jquery/dist/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
jquery.min.js:2 Uncaught ReferenceError: imlist is not defined
    at HTMLDocument.initJS16 (editor16.js:13)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
initJS16 @ editor16.js:13
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
r.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
favicon.ico:1 GET http://noc/favicon.ico 404 (Not Found)
```
but editor workly and I can edit map.

**Comment by pautiina** [comment]
And new error when I try change map properties;
```
editor.js:136 Uncaught TypeError: Cannot read property 'slice' of undefined
    at HTMLInputElement.help_handler (editor.js:136)
    at HTMLInputElement.dispatch (jquery.min.js:3)
    at HTMLInputElement.q.handle (jquery.min.js:3)
help_handler @ editor.js:136
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
```
![image](https://user-images.githubusercontent.com/11805503/35729155-7b3e07fa-0816-11e8-9653-9a163e947bf4.png)

**Comment by netniV** [comment]
imlist comes from EditorUI.php:
```php
$imagesJSON = "\nvar imlist = " . json_encode($imageList) . ";\n";
$tpl->set("images_json", $imagesJSON);
```

editor-resources/template/main-oldstyle.php and main.php output $images_json:
```html
    <script type="text/javascript">
        <?php echo $map_json; ?>
        <?php echo $images_json; ?>
        <?php echo $fonts_json; ?>
        <?php echo $editor_settings; ?>

        var $global_settings = <?php echo $global; ?>;
        var $global_settings2 = <?php echo $global2; ?>;
        var editor_url = '<?php echo $editor_name; ?>';
        var fromplug = <?php echo $fromplug ?>;
        var host_url = <?php echo host_url ?>;
    </script>
```
The `editor-resources/editor16.js` should probably check whether imlist is null before looping through it though:

```javascript
function initJS16() {

    jQuery.each(imlist, function (index, value) {
        // slot in the list of images in:
        //    node icon selectbox
        //    map background image
        var newitem = jQuery("<option />").attr("value", value).text(value);
        jQuery(".imlist").append(newitem);
    });

    jQuery.each(fontlist, function (index, value) {
        // slot in the list of fonts in each of the select boxes where they are expected
        var newitem = jQuery("<option />").attr("value", value).text(value);
        jQuery(".fontlist").append(newitem);
    });
```

Should become:

```javascript
function initJS16() {   

    if (imlist != null) 
    jQuery.each(imlist, function (index, value) {
        // slot in the list of images in:
        //    node icon selectbox
        //    map background image
        var newitem = jQuery("<option />").attr("value", value).text(value);
        jQuery(".imlist").append(newitem);
    });

    if (fontlist != null)
    jQuery.each(fontlist, function (index, value) {
        // slot in the list of fonts in each of the select boxes where they are expected
        var newitem = jQuery("<option />").attr("value", value).text(value);
        jQuery(".fontlist").append(newitem);
    });
```

Though @howardjones may find that this is a problem elsewhere since they shouldn't actually be null.  You could add a `debugger;` statement as the first line of `initJS16()` to check that

**Comment by howardjones** [comment]
No, it should check. Or it shouldn't be included on the front-oldstyle.php template. That's where this error shows up (for me anyway), because in the front page, the same variable dump doesn't happen, so they are null. The better way is probably to break out any javascript used on the front picker page into another file. I don't think there is much - just the thing that hides the warning that javascript isn't enabled.

**Comment by netniV** [comment]
One other thing I noticed from above, it's not just host_url that should be quoted... shouldn't the others too? $global, $global2 and $editor_settings?  (unless these are already defined as being arrays or quoted)

**Comment by howardjones** [comment]
No, they are created from json_encode() so they are already valid javascript objects.

**Comment by netniV** [comment]
I did wonder why they hadn't flagged up yet 👍

**Comment by dabeani** [comment]
thx so far, its working now for me :+1:

**Comment by pautiina** [comment]
Now these errors are not present.
But the editor is still not working properly.
The editor does not read the map parameters from the configuration file, nor does it change them.
![image](https://user-images.githubusercontent.com/11805503/35739038-1bd296fa-0839-11e8-958e-bb21e5424446.png)

**Comment by pautiina** [comment]
I also can not edit thith parametr for editor:
![image](https://user-images.githubusercontent.com/11805503/35739362-08f73b48-083a-11e8-8285-af2ba2d8de43.png)

**Comment by pautiina** [comment]
Not display button for choose **data sourse** , **info_url graph** and  **overlib graph**
![image](https://user-images.githubusercontent.com/11805503/35739930-ec28cffc-083b-11e8-813c-ab7075b7a469.png)

**Comment by howardjones** [comment]
No-one ever said the editor was working completely - it's been rewritten completely (apart from the javascript) since 0.98. The basic editing for nodes and links works, but quite a few things around the edges don't.

The picker link should show up though. I'll check that again. (although I already know you'll get a HTTP 500 error when the picker opens)

**Comment by pautiina** [comment]
When I open on browser url editor.php I have button for **[Pick from Cacti]** but when I click for this link I have error, but not HTTP 500:
![image](https://user-images.githubusercontent.com/11805503/35741883-9dd51f8a-0841-11e8-808c-700c5fc1d1df.png)

**Comment by netniV** [comment]
> No-one ever said the editor was working completely - it's been rewritten completely (apart from the javascript) since 0.98. The basic editing for nodes and links works, but quite a few things around the edges don't.

The editor isn't fully functionality 😱 🤣

**Comment by howardjones** [comment]
Well, yeah, but even more than before :-) But it's a lot easier to read than it used to be.

**Comment by pautiina** [comment]
Ok, now I have link for choose data source and it's work.

But I have many device on Cyrillic on UTF-8:

![image](https://user-images.githubusercontent.com/11805503/35768074-36a2d686-08ff-11e8-84f9-8f998937bc97.png)

**Comment by dabeani** [comment]
for me (austria) it works! thanks! perfect work, and thank you very much for your work on that.
But, if i want to create links between Nodes, i get following error:
weathermap-cacti10-plugin-mgmt.php // editor.js:84
Uncaught ReferenceError: NodeIDs is not defined
    at HTMLAreaElement.click_handler (editor.js:213)
    at HTMLAreaElement.dispatch (jquery.min.js:2)
    at HTMLAreaElement.y.handle (jquery.min.js:2)

**Comment by netniV** [comment]
@howardjones You're getting things closer so people's expectations are raising ;-)

**Comment by howardjones** [comment]
@dabeani That sounds like you might have an old version of `editor-resources/editor.js`... Will confirm though.

**Comment by howardjones** [comment]
Not sure why commit comments aren't appearing in the issue any more... Anyway, you can add links now @dabeani 
And @pautiina can look at (but not update) map properties. Still some work to do there.
Will have to figure out the utf8 stuff - I haven't done anything special there.

**Comment by netniV** [comment]
I tend to make sure to add # and the issue number somewhere just so it shows up

**Comment by howardjones** [comment]
Forgot to push. D'oh. That wasn't it last time though.

**Comment by howardjones** [comment]
@pautiina I am able to see Cyrillic hostnames in the picker now with 5c3d53b

**Comment by pautiina** [comment]
@howardjones Many thanks. Really. Now normally displayed.

**Comment by pautiina** [comment]
Hello.
I have retest the latest code. Visual editor work normally.
But when I choose device for data source my browser print some php notice:

```Notice: Undefined index: target in /var/www/data/cacti/plugins/weathermap/lib/Weathermap/Integrations/Cacti/EditorDataPicker.php on line 147```

![image](https://user-images.githubusercontent.com/11805503/36368476-16fd69fa-1560-11e8-866b-09827b4d2630.png)

**Comment by netniV** [comment]
I think there is a change that @howardjones is working on.  If I recall over the weekend I saw that he had not pushed it out yet because it relied on another change.  This may be related (or not 🤷‍♂️ )

**Comment by howardjones** [comment]
No, this is a bug. I'll take a look later today.
